# Calculating the Accuracy of the Model

Using the same dataset, expand the model by including all other features into the regression. 

Moreover, calculate the accuracy of the model and create a confusion matrix

## Import the relevant libraries

In [70]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

## Load the data

Load the ‘Bank_data.csv’ dataset.

In [71]:
raw_data = pd.read_csv('Bank_data.csv')

In [72]:
raw_data.describe(include='all')

,Unnamed: 0,interest_rate,credit,march,may,previous,duration,y
count,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000,518
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259
mean,258.500000,2.835776,0.034749,0.266409,0.388031,0.127413,382.177606,NaN
std,149.677988,1.876903,0.183321,0.442508,0.814527,0.333758,344.295990,NaN
min,0.000000,0.635000,0.000000,0.000000,0.000000,0.000000,9.000000,NaN
25%,129.250000,1.042750,0.000000,0.000000,0.000000,0.000000,155.000000,NaN
50%,258.500000,1.466000,0.000000,0.000000,0.000000,0.000000,266.500000,NaN
75%,387.750000,4.956500,0.000000,1.000000,0.000000,0.000000,482.750000,NaN
max,517.000000,4.970000,1.000000,1.000000,5.000000,1.000000,2653.000000,NaN

In [73]:
raw_data
data = raw_data.copy()
data['y'] = data['y'].map({'yes':1,'no':0})
data.head()

   Unnamed: 0  interest_rate  credit  march  may  previous  duration  y
0           0          1.334     0.0    1.0  0.0       0.0     117.0  0
1           1          0.767     0.0    0.0  2.0       1.0     274.0  1
2           2          4.858     0.0    1.0  0.0       0.0     167.0  0
3           3          4.120     0.0    0.0  0.0       0.0     686.0  1
4           4          4.856     0.0    1.0  0.0       0.0     157.0  0

### Declare the dependent and independent variables

Use 'duration' as the independet variable.

In [74]:
x1 = data['duration']
y = data['y']

### Simple Logistic Regression

Run the regression and graph the scatter plot.

In [75]:
x = sm.add_constant(x1)
reg = sm.Logit(y,x1)
res_log = reg.fit()
res_log.summary()

Optimization terminated successfully.
         Current function value: 0.641883
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      517
Method:                           MLE   Df Model:                            0
Date:                Sun, 04 May 2025   Pseudo R-squ.:                 0.07396
Time:                        12:05:38   Log-Likelihood:                -332.50
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
duration       0.0014      0.000      6.535      0.000       0.001       0.002
==============================================================================
"""

## Expand the model

We can be omitting many causal factors in our simple logistic model, so we instead switch to a multivariate logistic regression model. Add the ‘interest_rate’, ‘march’, ‘credit’ and ‘previous’ estimators to our model and run the regression again.

### Declare the independent variable(s)

In [76]:
x1 = data[['interest_rate','march','credit','previous']]
y = data['y']

In [77]:
reg_logit = sm.Logit(y,x1)
res_log = reg_logit.fit()
res_log.summary2()

Optimization terminated successfully.
         Current function value: 0.579994
         Iterations 7

<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Logit
=================================================================
Model:              Logit            Method:           MLE
Dependent Variable: y                Pseudo R-squared: 0.163
Date:               2025-05-04 12:05 AIC:              608.8740
No. Observations:   518              BIC:              625.8739
Df Model:           3                Log-Likelihood:   -300.44
Df Residuals:       514              LL-Null:          -359.05
Converged:          1.0000           LLR p-value:      3.0528e-25
No. Iterations:     7.0000           Scale:            1.0000
-----------------------------------------------------------------
                   Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
-----------------------------------------------------------------
interest_rate     -0.1719   0.0310 -5.5437 0.0000 -0.2326 -0.1111
march             -0.4125   0.2089 -1.9748 0.0483 -0.8219 -0.0031
credit             2.7040   1.0424  2.5941 0.0095  0.6610  4.7470
previous           2.4739   0.4344  5.6951 0.0000  1.6225  3.3253
=================================================================

"""

### Confusion Matrix

Create the confusion matrix of the model and estimate its accuracy.

<i> For convenience we have already provided you with a function that finds the confusion matrix and the model accuracy.</i>

In [78]:
def confusion_matrix(data,actual_values,model):
        
        # Confusion matrix 
        
        # Parameters
        # ----------
        # data: data frame or array
            # data is a data frame formatted in the same way as your input data (without the actual values)
            # e.g. const, var1, var2, etc. Order is very important!
        # actual_values: data frame or array
            # These are the actual values from the test_data
            # In the case of a logistic regression, it should be a single column with 0s and 1s
            
        # model: a LogitResults object
            # this is the variable where you have the fitted model 
            # e.g. results_log in this course
        # ----------
        
        #Predict the values using the Logit model
        pred_values = model.predict(data)
        # Specify the bins 
        bins=np.array([0,0.5,1])
        # Create a histogram, where if values are between 0 and 0.5 tell will be considered 0
        # if they are between 0.5 and 1, they will be considered 1
        cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
        # Calculate the accuracy
        accuracy = (cm[0,0]+cm[1,1])/cm.sum()
        # Return the confusion matrix and 
        return cm, accuracy

In [79]:
confusion_matrix(x,y,res_log)

ValueError: shapes (518,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)